src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/CollectionExercise.java

Needed to tweak the data model

Enhance data model

---

pom.xml

We need to move off Census projects and onto long-term ONS ones.
Dropped in the new CI project.
Try to build & push.
Trello: https://trello.com/c/y3WhajYP

Migrate to new CI project

---

src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/BulkProcess.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/CollectionExercise.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/Job.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/JobRow.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/JobRowStatus.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/JobStatus.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/User.java

We needed staging tables for sample load.
Added staging tables.
Part of multi-PR change.
Trello: https://trello.com/c/nQcV7H7N

Add sample staging DB tables & link to collex

---

src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/BulkProcess.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/Job.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/Survey.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/User.java

Sample is flexible so validation needs to be too.
Added JSONB sample validation config blob to survey.
Create a survey with the following sample validation config JSON:
```json
[
{
"columnName": "ADDRESS_LINE1",
"rules": [
{
"className": "uk.gov.ons.ssdc.supporttool.validation.MandatoryRule"
},
{
"className": "uk.gov.ons.ssdc.supporttool.validation.LengthRule",
"maxLength": 60
}
]
},
{
"columnName": "ADDRESS_LINE2",
"rules": [
{
"className": "uk.gov.ons.ssdc.supporttool.validation.LengthRule",
"maxLength": 60
}
]
},
{
"columnName": "ADDRESS_LINE3",
"rules": [
{
"className": "uk.gov.ons.ssdc.supporttool.validation.LengthRule",
"maxLength": 60
}
]
},
{
"columnName": "TOWN_NAME",
"rules": [
{
"className": "uk.gov.ons.ssdc.supporttool.validation.MandatoryRule"
}
]
},
{
"columnName": …
```

Configurable sample validation

---

pom.xml
src/test/resources/docker-compose.yml

Postgres 11 bad. Postgres 13 good.
11 -> 13
Build & check it still works.
Trello: https://trello.com/c/RoAn2AVn

Upgrade to Postgres 13

---

.codecov.yml
.travis.yml

Travis is dead good.
Enabled Travis build again.
See if Travis is doing the do.
Trello: https://trello.com/c/s7n9mKb7

Re-enable Travis build

---

pom.xml
src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/CaseToProcess.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/FulfilmentToProcess.java
src/main/resources/application.yml
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/DeactivateUacReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/InvalidAddressIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/ReceiptReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/RefusalReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/SampleLoadedIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/SurveyLaunchedReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/TelephoneCaptureReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/UpdateSampleSensitiveReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/model/repository/ActionRuleSurveyPrintTemplateRepository.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/model/repository/FulfilmentSurveyPrintTemplateRepository.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/ActionRuleIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/FulfilmentIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/testutils/DeleteDataHelper.java

We were running on a version of Spring Boot from May 2020.
Upgraded to the latest and greatest Spring Boot.
Run the ATs. Should be zero regression.
Trello: https://trello.com/c/8MZx3DE9

Upgrade to Spring Boot v2.5.2

---

src/main/java/uk/gov/ons/ssdc/caseprocessor/service/CaseService.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/service/DeactivateUacProcessor.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/service/PrintProcessor.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/service/UacService.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/utils/EventHelper.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/utils/EventHelperTest.java

Need to have consistent naming on our events
* Use `EventHelper` consistently
Run the tests, make sure they still pass
https://trello.com/c/u1GEyNYO/2508-what-the-heck-is-the-caseservice

2508 consistent event naming

---

src/main/java/uk/gov/ons/ssdc/caseprocessor/service/PrintProcessor.java

We shouldn't leave dead code lying around.
Deleted dead code.
Zero regression.
Trello: https://trello.com/c/6w04h0Ab

Remove dead code

---

.github/workflows/codeql-analysis.yml

enabling CodeQL Security Analysis tool so we can trial the usage of it
- added a codeql analysis file

create codeql file

---

src/main/resources/application.yml

Case processor is refusing to start up in GCP.
Added pubsub emulator config to disable emulator.
Try it.
Trello: https://trello.com/c/yPZ72ten

Fix pusbub emulator host required problem

---

pom.xml

We want to ask the user if they want to proceed with a sample file if some of the rows have failed validation, or cancel the job.
Validation now happens after staging of a sample file, but then the support tool waits for the user to either process the file or cancel the job.
ATs should all pass as before.
Manual scenarios to check are:
1. Check that sample pauses after validation
2. Check that sample loads after clicking "Process" and rows are deleted
3. Check that job rows are deleted after clicking "Cancel"
4. Check that sample with bad header is total failure, and all rows deleted
5. Check that sample with mismatched number of columns in a row is total failure, and all rows deleted
6. Check that sample with one row failing validation goes to "validated with errors" status, and good …

Validate sample in separate step from processing

---

.github/workflows/codeql-analysis.yml
pom.xml
src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/ActionRuleIT.java

`ssdc-rm-common-entity-model` was recently modified. Need to update the pom and get the tests passing.
Bump POM version, tweak codeql config and fix test
Run `mvn clean install`
https://trello.com/c/21FNrXpB/2864-bump-common-entity-versions-1

2864 - Bump common entity model version and fix failing tests

---

src/main/java/uk/gov/ons/ssdc/caseprocessor/utils/Constants.java

Bump schema version to latest
Schema version bump
Run the acceptance tests
https://trello.com/c/OcShPvHZ/2873-move-to-json-schema-v03-release-3

2873 - Update JSON schema version

---

pom.xml

The Spring "Data REST" auto-generated APIs are great for rapid application development, but the security features we need don't lend themselves readily to the pattern: we will end up exposing sensitive data, and creating a large attack surface, unless we are very careful.
Replaced all the Spring auto-generated APIs with handwritten ones, which have full security and only expose explicit data, which is allowed to be viewed to prevent accidental data breaches.
Every single feature of Support Tool has been affected, but there should be zero regression. Basically, do a full manual retest. Or, just trust me: I tested everything.
Trello: https://trello.com/c/qDr6CDkJ

Bump DDL version

---

pom.xml

RegEx is hard to understand, even for people who write the expressions. We should have a user-friendly message for users when validation fails.
Added a user friendly message.
Try loading a dodgy phone number in a sample and check that the better error message is displayed.
Trello: https://trello.com/c/MJdfbOyx

Bump common entity version

---

pom.xml

Minor change to DDL, bump version here for consistency
- Bump common entities version
Nothing to test
https://trello.com/c/uMBMYfs8/2787-support-tool-duplicate-permissions

2787 Bump common entities version

---

pom.xml

Bump common-entity-model version
Version bump
Build the common entity model and build all affected branches.  Check stuff still works.
- https://trello.com/c/rGcj9FUl
- https://github.com/ONSdigital/ssdc-rm-ddl/pull/59

Bump common-entity-model version

---

pom.xml
src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/ActionRuleIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/FulfilmentIT.java

Bump common entities and fix tests.
Bumped.
Run ATs.
Trello: https://trello.com/c/TvoPKktF

Bump common entities and fix tests

---

pom.xml

bump to 4.3 common
With others from ticket
https://trello.com/c/TcD3078i/2980-bulk-processor-sample-sensitive-and-sample-updates-and-invalid-back-end-8

bump to 4.3 common

---

src/main/java/uk/gov/ons/ssdc/caseprocessor/config/AppConfig.java
src/main/resources/application.yml
src/main/resources/logback.xml

Nicer logging
Locally with docker dev, check nothing broken, logs look similar to before
In GCP with K8s branch.  
https://trello.com/c/CaG0Bhuj/3054-use-structured-logging-in-all-our-java-services-3

add logback

---

src/main/java/uk/gov/ons/ssdc/caseprocessor/config/AppConfig.java

new fangled json logging broke local logging
Make the json log conditional on profile
Make it log and check the output is there for log with style messages
https://trello.com/c/B4tUlG3N/3090-fix-local-logging-3

local logging fix

---

src/main/java/uk/gov/ons/ssdc/caseprocessor/config/AppConfig.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/ActionRuleScheduler.java

Missing {} on loading logging profile

Logging fix

---

Makefile

make make files consistent
https://trello.com/c/SyngGfnM/3153-standardise-makefiles-2-day

make consistent

---

pom.xml

bump common

---

.travis.yml
Makefile
pom.xml
src/test/resources/docker-compose.yml

We are moving our images to an artifact registry.
- Update image URIs
Check the new image URIs are correct
https://trello.com/c/0LziJk8R/3213-migrate-from-container-registrys-to-artifact-registry-using-standard-repository-8

3213 Migrate from container registry to artifact registry

---

exclude-pmd.properties
src/main/java/uk/gov/ons/ssdc/caseprocessor/utils/HashHelper.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/utils/pseudorandom/PseudorandomNumberGenerator.java

PMD raised an issue around class level MessageDigest, thread safe etc.
Get new instance each tim
Zero regression
https://trello.com/c/SIFeKgmH/3306-spike-java-pmd-best-practice-avoidmessagedigestfield-05-day

No class level MessageDigest, always get new Instance

---

exclude-pmd.properties
src/main/java/uk/gov/ons/ssdc/caseprocessor/cache/UacQidCache.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/utils/LuhnHelper.java

PMD check has identified a few classes which don't make full use of passing exception details through.
Fixed exception handling recommended by PMD check
Ensure it still builds 
https://trello.com/c/Zmm62ErR

3308 Fix PMD PreserveStackTrace Warning

---

exclude-pmd.properties
pom.xml

Bump versions, remove pmd useVarAgrs
Zero regression

bump common versions

---

src/test/resources/docker-compose.yml
src/test/resources/java_healthcheck/HealthCheck.java

twasn't working before and we still need a healtheck (ok it worked without one, but that was by lucky timings)
Add java healthcheck
make build

add java style healthcheck

---

src/main/java/uk/gov/ons/ssdc/caseprocessor/model/repository/UacQidLinkRepository.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/service/UacService.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/ReceiptReceiverTest.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/service/UacServiceTest.java

QID is the new kid on the block, down with questionnaire id
renaming
With others from ticket
https://trello.com/b/VS0ZyRmj/srm

questionnaire out qid in

---

pom.xml
src/test/java/uk/gov/ons/ssdc/caseprocessor/collectioninstrument/RulesCacheTest.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/testutils/JunkDataHelper.java

work with new collexIntrumentRule
with others from ticket
https://trello.com/c/jxMboyx6/549-send-metadata-from-sample-data-to-eq-for-routing-piping-and-linking-13

update collex instrument rule

---

src/main/java/uk/gov/ons/ssdc/caseprocessor/service/ExportFileProcessor.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/ActionRuleIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/FulfilmentIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/service/ExportFileProcessorTest.java

PHM want it
| ,
make test and ATs off ticket
https://trello.com/c/nrt6p8tf/749-print-file-change-separator-3

replace | with , in export rows

---

pom.xml
src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/ActionRuleIT.java

We've updated the common entities, it needs bumping here and a couple of test setups updated to match.
Note this is expected to fail it's build/tests until the new artifact version is merged/built/released.
- Bump common entities
- Fix test setup
Check the updates, build the [common entities change](https://github.com/ONSdigital/ssdc-rm-ddl/pull/153) locally, append `-SNAPSHOT` to the changed version in the pom and run `make build` to see the build pass locally.
https://trello.com/c/1e49eAhh/1256-bump-common-entities-versions
https://trello.com/c/gL7KBQtj/1043-govnotify-create-an-additional-service-13

1256 Bump common entities, update integration tests

---

python_spike/caseprocessor/db/db_utility.py
python_spike/caseprocessor/decorators/transaction_decorators.py

This branch adds an implementation of Python transaction handling covered by this [Spike](https://github.com/ONSdigital/ssdc-rm-documentation/pull/234/files#diff-7863fd55e307cb594b4b0daff444928ccba79d08671a07524d3a88bbfd29d2c7)
Added the transaction handling decorators with appropriate logging
Nothing to test yet, still needs to be implemented 
The mechanism has been tested on this docker-dev [branch](https://github.com/ONSdigital/ssdc-rm-docker-dev/tree/1346-spike-transaction-handling-in-python)
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=2913&view=detail&selectedIssue=SDCSRM-260

Python transaction handling

---

pom.xml
src/main/java/uk/gov/ons/ssdc/caseprocessor/collectioninstrument/CollectionInstrumentHelper.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/config/AppConfig.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/ManagedMessageRecoverer.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/PrintFulfilmentReceiver.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/ActionRuleScheduler.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/ActionRuleTriggerer.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/ClusterLeaderManager.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/ClusterLeaderStartupManager.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/FulfilmentProcessor.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/FulfilmentScheduler.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/MessageToSendProcessor.java
src/main/resources/logback.xml
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/PrintFulfilmentReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/PrintFulfilmentReceiverTest.java

The logging framework we were using is no longer supported
Switched to using Slf4j

Use Logback with SLF4J instead of godaddy logger

---

pom.xml
src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/ActionRuleIT.java

The common entities have been updated.
- Bump the common entities version
- Fix tests that had null values in the action rule status
No functional change, the tests should pass once the DDL repo change has been merged and the new artifact built.
https://jira.ons.gov.uk/browse/SDCSRM-577

SDCSRM-577 Bump common entities version and fix tests

---

README.md
src/main/java/uk/gov/ons/ssdc/caseprocessor/config/MessageConsumerConfig.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/service/CaseService.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/service/DeactivateUacProcessor.java
src/main/java/uk/gov/ons/ssdc/caseprocessor/service/UacService.java
src/main/resources/application-dev.yml
src/main/resources/application.yml
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/DeactivateUacReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/EmailFulfilmentReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/EqLaunchReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/InvalidCaseReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/NewCaseReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/PrintFulfilmentReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/ReceiptReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/RefusalReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/SmsFulfilmentReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/UpdateSampleReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/UpdateSampleSensitiveReceiverIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/ActionRuleIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/FulfilmentIT.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/service/CaseServiceTest.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/service/DeactivateUacProcessorTest.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/service/UacServiceTest.java
src/test/java/uk/gov/ons/ssdc/caseprocessor/testutils/PubsubHelper.java
src/test/resources/application-test.yml
src/test/resources/setup_pubsub.sh

We're not sharing our pubsub topics with any other teams so there's no need to have references to a shared pubsub project
- Removed references to shared pubsub project
- Run `make build`
- Run the branch with the ATs
[Jira](https://jira.ons.gov.uk/browse/SDCSRM-292)

Removed references to shared project for pubsub

---

.github/workflows/mega-linter.yml
.gitignore
.markdownlint.yaml
.mega-linter.yml
Makefile
README.md

Adding Mega linter
Config for mega linter and markdownlint
Fixed any failures
Check that everything still works. 
The Git Action should run and pass on this PR.
[SDCSRM-634](https://jira.ons.gov.uk/browse/SDCSRM-634)

Add megalinter and fix any issues

---

pom.xml

Common entity needed to be bumped
Bumped common entity
Build DDL changes
add -SNAPSHOT to the end of the version
run `make build`
https://officefornationalstatistics.atlassian.net/browse/SDCSRM-1071

SDCSRM-1071 Bump common entity
