ONSdigital/ssdc-rm-caseprocessor

- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/User.java
`user` is a reserved word in SQL. Causes problems with DDL and stuff.
Changed user table to be called users... same solution as with cases table.
Start everything. Does it work?
Trello: https://trello.com/c/EJIfiW4G
> Fix user reserved word

- src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/ClusterLeaderManager.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/WaveOfContactTriggerer.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/WaveOfContactTriggererTest.java
Each case processor is logging 64 times per minute, which is quite chatty.
Reduced the cluster leader locking logging from info to debug.
Run it. Follow the logs.
Trello: https://trello.com/c/j269XaXl
> Reduce log chattiness

- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/User.java
Hibernate DDL generation is not lining up perfectly.
Used explicit table naming for `users_surveys` table.
Build a GCP environment with the `apply.sh` script.
Trello: https://trello.com/c/4xu8QHn4
> Fix DDL mapping pain

- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/SampleReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/CaseService.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/SampleLoadedIT.java
A CASE_CREATED event needs to be emitted to all interested parties(queues) when a case is created on sample load.  
A CASE_CREATED event is emitted to the outbound events exchange.  Follows a similar pattern to that of the census-rm-case-processor.  Note - there are a few test queues that aren't required but these are being tidied up as part of a separate ticket in progress, along with the queue names.
- Build and run the tests
- Load a sample in and a CASE_CREATED event should be output for each case created from the sample.
- https://trello.com/c/GPErJ5Zi
> Emit a CASE_CREATED event on sample load

- src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/ClusterLeaderManager.java
Multiple threads are in a race to record in the database that the host is the leader. This means that multiple attempts are made to write the same database row, resulting in this error: `ERROR: duplicate key value violates unique constraint "cluster_leader_pkey"`
This is harmless, but people are bound to whinge about the error in the logs.
Created a locking mechanism to lock out all but one thread from attempting to declare itself as cluster leader.
Ensure the `cluster_leader` table is empty, then start the case processor and check the logs for the error.
Trello: https://trello.com/c/6RLzuoyn
> Fix leader election thread contention using locking

- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/DeactivateUacReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/ReceiptReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/PrintProcessor.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/UacService.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/DeactivateUacReceiverTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/ReceiptReceiverTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/service/PrintProcessorTest.java
When we use Hibernate/JPA/Spring Data to save stuff to the database, we need to do it properly.
Wrong:
```java
MyEntity myEntity = new MyEntity();
myRepository.save(myEntity);
// do more stuff
myRepository.save(myEntity); // NOPE! You just wiped out a bunch of stuff!
```  
Right:
```java
MyEntity myEntity = new MyEntity();
myEntity = myRepository.save(myEntity); // YES! This is how you do it!
// do more stuff
myRepository.save(myEntity);
```  
Fixed dodgy code.
However you want, but mainly, check that the created dates are not being destroyed any more on the UacQid links.
Trello: https://trello.com/c/hgu9MSur
> Fix bug with created date getting wiped out from UacQidLink

- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/Job.java
Performance was bad, when testing with a 450k sample.
Removed the `cascade = CascadeType.ALL` from the JobRows, so that Hibernate wouldn't have to figure out if we had fiddled with any of the rows, every time we update the Job progress.
Load a 450k sample. Profit.
Trello: https://trello.com/c/0eA4YuSI
> Fix performance issues with JobRows

- README.md
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/CaseService.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/DeactivateUacProcessor.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/UacService.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/utils/Constants.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/DeactivateUacReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/service/DeactivateUacProcessorTest.java
- src/test/resources/definitions.json
Routing key != queue name. If you want to send directly to a queue, use the default exchange. Otherwise, use the `events` exchange with a meaningful routing key.
Named the routing keys better.
Run the ATs. Should be zero regression.
Trello: https://trello.com/c/4CgML4w6
> Consistent routing keys

- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/PrintProcessor.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/service/PrintProcessorTest.java
Wording was unclear for users, perhaps leading them to believe that printed materials had been posted out to respondents, when it had not.
Changed wording to make it clear that a file has been generated, but has probably not been sent to the printer supplier yet.
Try it.
Trello: https://trello.com/c/qIdPbsJG
> Improve wording of print file generation

- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/SampleReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/EventType.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/logging/EventLoggerTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/SampleLoadedIT.java
CASE_CREATED & UAC_UPDATED are unused (database) event types.
SAMPLE_LOADED is misleading, because it does not tell us when a sample was loaded, but in fact when we received an instruction to create a case.
We should get rid of SAMPLE_LOADED and UAC_UPDATED and store a CASE_CREATED when we create a case.
Removal of bad events
Updated tests
Build images and run ATs
https://trello.com/c/JnLxj02F
> Removal of Bad Events

- src/test/resources/docker-compose.yml
Integration tests fail because UAC-QID service is never seen as healthy.
Pointed healthcheck at correct endpoint.
Build with `mvn clean install` and it should pass.
Trello: https://trello.com/c/fNCyBh3m
> Fix broken ITs because of new health endpoint for UAC-QID Service

- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/Survey.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/FulfilmentIT.java
We can't currently load business samples into _Strategic_ Survey Data Collection, because we insist on there being a header row, and we expect regular vanilla CSV (C standing for comma, not colon).
Added flag to indicate sample has no header row, and configurable sample file seperator.
Try loading a business sample.
Trello: https://trello.com/c/Ies3dYbl
> Allow sample with different delimiter & no header to be loaded

- src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/CaseClassifier.java
Spring Boot 2.5.2 deprecates StringUtils.isEmpty.
Used `StringUtils.hasText` instead.
Zero regression.
Trello: https://trello.com/c/f7yh1qjL
> Replace deprecated StringUtils.isEmpty with hasText

- src/main/java/uk/gov/ons/ssdc/caseprocessor/utils/RedactHelper.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/UpdateSampleSensitiveReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/utils/RedactHelperTest.java
When we redact a value, we should be able to find out which value was changed or blanked out, but previously we were replacing ALL the sensitive data with "REDACTED" -> "REDACTED" which told us very little about what actually got changed.
Only redact values, not keys.
Use the wizarding ways.
Trello: https://trello.com/c/R1sxFecV
> Stop redacting sensitive keys & data when blanking

- src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/ClusterLeaderManager.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/ClusterLeaderManagerStartup.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/ClusterLeaderStartupManager.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/testutils/DeleteDataHelper.java
Leader election was spitting out errors into the logs, and I suspect that it might be the reason why we have an integration test which fails occasionally.
Got rid of the complex locking in favour of much simpler locking. Handled the dead heat in a more elegant and explicit way. Generally simplified and improved.
Ensure that the table `cluster_leader` is empty, then start Case Processor up. You should see zero errors on startup (before you would have seen some kind of key violation occasionally).
Trello: https://trello.com/c/68HFsjax
> Simplify and improve leader election

- src/main/java/uk/gov/ons/ssdc/caseprocessor/healthcheck/HeathCheck.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/healthcheck/HeathCheckIT.java
HealthCheckIT was failing quite frequently... especially if ever run on the change of hour.
Fixed it to check the time difference, not by looking at the first n characters of the date as an ISO string.
Run the IT.
Trello: https://trello.com/c/cDKl8nne
> Fix unreliable HealthCheckIT

- src/main/java/uk/gov/ons/ssdc/caseprocessor/Application.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/config/AppConfig.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/config/MessageConsumerConfig.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/config/OurProjectPubsubConfig.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/config/SharedProjectPubsubConfig.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/MessageSender.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/entity/MessageToSend.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/MessageToSendSender.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/PrintProcessor.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/SampleLoadedIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/TelephoneCaptureReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/ActionRuleIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/FulfilmentIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/service/PrintProcessorTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/testutils/PubsubHelper.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/testutils/TestConfig.java
- src/test/resources/application-test.yml
- src/test/resources/setup_pubsub.sh
RM doesn't 'own' the topics and subscriptions which are used to integrate between other products... and as such, they should be kept in a shared project.
Use our own project only for internal messaging, otherwise use a shared project.
Build Case Processor and Support Tool, then start everything up in docker dev with `make up` and then run the acceptance tests with `make test`... should be zero regression.
Trello: https://trello.com/c/yPZ72ten
> Use shared project for shared pubsub topics and subscriptions

- src/main/java/uk/gov/ons/ssdc/caseprocessor/config/OurProjectPubsubConfig.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/config/SharedProjectPubsubConfig.java
For some unknown reason, Spring is spitting its dummy about `GcpPubSubProperties` when in GCP.
Removed need for `GcpPubSubProperties` class.
Try it.
Trello: https://trello.com/c/yPZ72ten
> Remove dependency on GcpPubSubProperties

- pom.xml
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/PrintFulfilmentReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/CaseToProcessProcessor.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/PrintProcessor.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/utils/EventHelper.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/service/CaseToProcessProcessorTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/service/PrintProcessorTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/utils/EventHelperTest.java
We should be able to correlate a fulfilment _request_ with the subsequent printing of it, which happens when fulfilments trigger.
Stored the correlation ID and originating user against fulfilments in the table where they are held, waiting until the trigger time arrives.
Run the ATs. Try using the Support Tool to request a paper fulfilment.
Trello: https://trello.com/c/v3nc5EHo
> Fulfilments use correct correlation ID and originating user

- pom.xml
- src/main/java/uk/gov/ons/ssdc/caseprocessor/config/MessageConsumerConfig.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/EqLaunchReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/CaseUpdateDTO.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/EqLaunchDTO.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/PayloadDTO.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/CaseService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/EqLaunchReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/EqLaunchReceiverTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/UacAuthenticationReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/service/CaseServiceTest.java
- src/test/resources/setup_pubsub.sh
"survey launch" is misleading, because a survey is a set of collection exercises, and a set of collection instruments... what we're really talking about is a specific electronic questionnaire launch (which could be either Blaise or EQ).
We need to rename the topic, subscription, listener in case processor and all associated gubbins.
Survey launch has been changed to eq launch in all occurrences
`shift-ctrl-f` for surveyLaunch(ed), survey-launch, survey_launch - should be zero occurrences
Build all the services on the ticket, check they all build successfully
Run the ATs using the branch on the ticket
https://trello.com/c/hOoco1AN/2752-rename-surveylaunch-to-eqlaunch-5
> Rename surveylaunch eqlaunch

- pom.xml
- src/main/resources/application.yml
- src/test/resources/docker-compose.yml
It's a pain when we're making model changes, because we have to build case processor before the integration tests start passing in the other projects: Case API, Notify Service & Response Operations.
Also, having to remember to generate DDL changes in a different repo, when the model has been changed, is something that's easily forgotten/overlooked.
Combined the DDL and common entities repos. Built a Postgres image which we can use in all the repos that use the common data model.
Run the integration tests in all the projects... should still work.
Trello: https://trello.com/c/EBa69kMx
> Combine DDL and entities into one repo to rule them all

- src/main/java/uk/gov/ons/ssdc/caseprocessor/config/AppConfig.java
There is some evidence of thread starvation, causing parallel sample loads to interfere with each other, and causing the heartbeat/healthcheck thread to be unable to update the keepalive, resulting in K8S pods being bounced that should not be.
Added a 'default' `taskScheduler` for Spring Boot to use.
It's hard... but try running multiple sample loads simultaneously. In truth though, we won't really know if this has improved anything until it's had a chance to 'soak' in the integration environment for a while.
Trello: https://trello.com/c/MPRzPGqL
> Create default task scheduler

- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/EqLaunchReceiver.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/EqLaunchReceiverTest.java
There was a bug.
Made bug go away.
Send in an eqLaunch event and check that there's a payload on the event when it's saved in the database.
Trello: https://trello.com/c/YP6PqJd7
> Fix null payload for eqLaunch events

- src/main/resources/application.yml
We need to set spring.cloud.gcp.pubsub.subscriber.flow-control.max-outstanding-element-count to some reasonable value, because unlimited is leading to many messages being processed more than once.
Setting added
Build, deploy to your GCP env and load a sample.
https://trello.com/c/LuJLtwKH/2920-set-maxoutstandingelementcount-in-microservices-which-pull-from-pubsub-3
> Set max outstanding element setting on pubsub

- pom.xml
- src/test/java/uk/gov/ons/ssdc/caseprocessor/testutils/JunkDataHelper.java
To comply with [v0.3_RELEASE](https://github.com/ONSdigital/ssdc-shared-events/blob/main/event_dictionary/v0.3_RELEASE/surveyUpdate.schema.json) of the shared events (JSON schema / event dictionary) and to comply with [0.4.0-DRAFT](https://github.com/ONSdigital/ssdc-shared-events/blob/main/event_dictionary/v0.4_RELEASE/surveyUpdate.schema.json) we have to emit `surveyUpdate` events to the `event_survey-update` topic.
Added UI form input sections to allow the users setting up surveys to specify the URL of the sample definition, which should be documented, versioned etc.
Also added input section for metadata.
Then, emitted the event when the survey has been inserted into the database.
Create a survey. Have a look at the `surveyUpdate` event which was emitted.
Trello: …
> Bump common entities

- .travis.yml
- pom.xml
- src/test/resources/application-test.yml
- src/test/resources/docker-compose.yml
The Docker containers needed to make the integration tests clash with each other on ports, so can't be run at the same time as other projects/repos.
Juggled the ports around to make them independent. Also, other fiddly stuff so that all the images/containers don't clash.
Try building two or more projects at the same time, and it should work with no problems.
Trello: https://trello.com/c/4FrIJ1LW
> Allow simultaneous builds

- pom.xml
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/CaseUpdateDTO.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/CaseService.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/UpdateNewCaseSensitiveReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/service/CaseServiceTest.java
Emit redacted sensitive data on case update
Adds sensitive data and.... redacts it
Run the tests, run the ATs on the ticket
https://trello.com/c/3ZKcJtYK/3012-sensitive-data-to-be-included-on-case-update-event-but-redacted-5
> Add and Redact SampleSensitive to caseUpdated Events

- pom.xml
- src/main/java/uk/gov/ons/ssdc/caseprocessor/config/MessageConsumerConfig.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/EmailFulfilmentReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/EmailRequest.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/EnrichedEmailFulfilment.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/PayloadDTO.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/CaseToProcessProcessor.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/EmailProcessor.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/utils/RedactHelper.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/EmailFulfilmentReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/EmailFulfilmentReceiverTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/model/repository/EmailTemplateRepository.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/model/repository/SmsTemplateRepository.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/ActionRuleIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/service/EmailProcessorTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/testutils/JunkDataHelper.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/testutils/TestConstants.java
- src/test/resources/setup_pubsub.sh
We should be able to send emails, either in a batch (action rule) or individually ad-hoc (fulfilment).
Added EMAIL action rule type implementation, and also listen for internal messages requesting email fulfilment, and events coming from Notify Service, recording that a fulfilment has happened against a case.
Run the ATs. Try sending in some events on topic `rm-internal-email-fulfilment`. Check the integration with Notify Service by requesting some email fulfilments in the Support Tool.
Trello: https://trello.com/c/OPYjtKwf
> Add email functionality

- .travis.yml
our travis builds are failing often due to dockerhub rate limiting failures, to solve this we need to log into an dockerhub enterprise account
- added a second docker login command line into .travis to use a enterprise dockerhub account
- trigger tests in travis and make sure it doesn't fail
> add a second docker login into travis file

- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/UacUpdateDTO.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/UacService.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/utils/Constants.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/service/UacServiceTest.java
We have released `0.5.0` of the [shared events](https://github.com/ONSdigital/ssdc-shared-events) so it's time to bring our microservices in line with that spec.
Changed all the microservices to publish `0.5.0` as the event version in the headers, and do a few other tweaks to meet the specification.
Also, allow some more versions to be sent to us for present and future needs.
Zero regression - ATs should pass.
Trello: https://trello.com/c/9uTTLrLW
> Migrate to shared events version 0.5.0 release

- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/EmailFulfilmentReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/InvalidCaseReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/PrintFulfilmentReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/RefusalReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/SmsFulfilmentReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/TelephoneCaptureReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/UpdateSampleReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/UpdateSampleSensitiveReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/repository/CaseRepository.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/CaseService.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/EmailFulfilmentReceiverTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/InvalidCaseReceiverTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/PrintFulfilmentReceiverTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/RefusalReceiverTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/SmsFulfilmentReceiverTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/TelephoneCaptureReceiverTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/UpdateSampleReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/UpdateSampleReceiverTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/UpdateSampleSensitiveReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/UpdateSampleSensitiveReceiverTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/service/CaseServiceTest.java
Attempting to simultaneously update more than one item of sample data, or sensitive sample data, can result in changes from one or the other of them being lost due to the overlapping attempts to write the same piece of JSON data.
Fundamentally, Postgres provides no functionality to only update a small part of a JSON binary blob column... the Postgres functions like `jsonb_set` are only convenience methods for manipulating JSON on Postgres, and do not change the fundamental thing that is happening: that the JSON is manipulated and then _replaced_ in its entirety, and as such, in the event that two SQL `UPDATE` statements are simultaneously executing, values will be overwritten by whatever was in memory at the time of update.
The only way to solve this "dead heat" problem is to lock the row …
> Fix simultaneous sample updates overwriting each other

- .travis.yml
- Dockerfile
- pom.xml
Java 11 is no longer the LTS (Long-Term Support) version. Java 17 is the LTS version, so we should use that.
Spring Boot 2.6.0 is the first version of Spring Boot to support Java 17, so we should use that too.
Upgraded to Java 17 and Spring Boot 2.6.0, plus upped any other versions required for everything to work.
Switched the Docker base image over to be JDK 17 too.
Zero regression.
Trello: https://trello.com/c/kcJGECdH
> Java 17 and spring boot 2 6 0

- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/ManagedMessageRecoverer.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/ManagedMessageRecovererTest.java
The Spring Google Pub/Sub libraries don't offer any obvious way to handle errors... it's fairly undocumented. Previously, we were manually nack'ing Pub/Sub messages that we wanted to be retried. On reflection, it would be better if Spring nack'ed the messages, because there's a concern that we might be nack'ing a message which Spring goes on to ack, creating a race condition between what we've done, and what Spring is trying to do.
Instead of nack'ing the message ourselves, we throw an exception, so that Spring nacks the message. However, this would cause unwanted logging, so we've changed the logging level to suppress the warnings about auto-nacking.
Send in some bad messages and make sure that they don't get lost.
Trello: https://trello.com/c/0WllcvES
> Use improved PubSub [auto] nacking for ManagedMessageRecoverer class

- pom.xml
- src/main/java/uk/gov/ons/ssdc/caseprocessor/config/MessageConsumerConfig.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/EmailFulfilmentReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/SmsFulfilmentReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/EmailConfirmation.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/EmailRequest.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/PayloadDTO.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/SmsConfirmation.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/SmsRequest.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/EmailProcessor.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/SmsProcessor.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/EmailFulfilmentReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/EmailFulfilmentReceiverTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/SmsFulfilmentReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/SmsFulfilmentReceiverTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/testutils/TestConstants.java
- src/test/resources/setup_pubsub.sh
Emails and sms from fulfilments and action rules are recorded the same in the event log. We want to be able to differentiate between these.
New flag added to dtos to mark if the email or sms is being sent as part of an action rule. This is sent as part of the message to notify service.
When the notify service has confirmed the message has been sent, the case processor records the event differently depending if it was fulfilment or action rule if the flag is present.
Renaming of return queue from notify service to confirmation from being named specifically fulfilment.
Build and make up with all other branches on card.
Run ATs
Check the emails and sms sent using action rules are recorded in the event log with the types ACTION_RULE_SMS_CONFIRMATION/ACTION_RULE_EMAIL_CONFIRMATION. …
> Differentiate between fulfilments and action rule sends in event log

- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/CaseUpdateDTO.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/CaseService.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/UpdateSampleReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/UpdateSampleSensitiveReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/service/CaseServiceTest.java
RM need to include the `caseRef`, `createdAt`, and `lastUpdatedAt` in `caseUpdate` messages (see [event dictionary](https://github.com/ONSdigital/ssdc-shared-events/blob/main/event_dictionary/0.5.0/caseUpdate.schema.json))
Added extra fields to caseUpdateDTO and populate.
Should still pass with ATs
https://trello.com/c/TBFVcPSY/3227-we-are-not-sending-caseref-as-part-of-the-eventcase-update
> 3227 - Add caseRef to case update events

- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/ExportFileProcessor.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/service/ExportFileProcessorTest.java
`peronalisation` can be `null` on valid fulfilment requests, this was causing a null pointer exception when the fulfilment was processed to send
- Allow null personalisation
- Add test cases
Follow the instructions on the support tool PR, send in a request for a template which has `__request__.` parameters but leave them empty. Trigger fulfilments to send. They should be processed without error even with `null` personalisation.
https://trello.com/c/dCFLqaY4/3245-support-tool-personalisation-on-print-fulfilment-requests-8
> 3245 Fix fulfilment personalisation null bug

- pom.xml
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/RefusalReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/RefusalDTO.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/RefusalTypeDTO.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/RefusalReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/RefusalReceiverTest.java
We need a new refusal type for anyone whos previously agreed to take part in a survey but now wants to withdraw. We also need functionality to remove sensitive data if a respondent asks us to remove their data.
- Added new withdrawal refusal type
- Remove sensitive data through the refusal event.
- Run with other branches and run the ATs
- Refuse a case and pass in `eraseData = true` and make sure the sensitive data in the event is removed
[Trello](https://trello.com/c/q8cx1tZn/)
> 3266 manage case withdrawals and data removal

- .mvn/jvm.config
- .travis.yml
- Makefile
- exclude-pmd.properties
- pom.xml
- src/main/java/uk/gov/ons/ssdc/caseprocessor/config/AppConfig.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/ManagedMessageRecoverer.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/NewCaseReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/UpdateSampleReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/messaging/UpdateSampleSensitiveReceiver.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/rasrm/client/RasRmPartyServiceClient.java
We can introduce PMD and ErrorProne code analysis/compile tools to our Java apps. Drawing from [this spike branch](https://github.com/ONSdigital/ssdc-rm-response-operations/pull/78/files) and adding some additional bits.
I’ve put a `<failurePriority>`  of `3` for PMD (scale of 1 - 5, with `1` being 'severe'), so it will fail on anything over a medium level severity. Anything below this level will output as a warning. I’ve set it at a level that seems sensible, but it’s debatable!
* Add PMD ignore file for code to be ignored for now, but to investigate later 
* Fix some errors & warnings from PMD
* Add `check` target to Makefile
* Update Travis checks
* If you want to see some of the PMD failures, comment out the lines in `exclude-pmd.propeties` file.
* Check to see the tools pick up the …
> 3277 - Add PMD and errorprone checks

- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/EmailConfirmation.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/SmsConfirmation.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/EmailFulfilmentReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/EmailFulfilmentReceiverTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/SmsFulfilmentReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/SmsFulfilmentReceiverTest.java
SMS and email fulfilments can now include personalisation from the request.
- Add personalisation to SMS and email fulilfment DTO
Run locally with linked branch, personalisation from SMS and email requests should be logged in the events but with redacted values.
https://trello.com/c/8DGOfdJx/3246-personalisation-on-sms-and-email-fulfilments-8
> 3246 Personalisation on SMS and email fulfilments

- Makefile
- pom.xml
The spotify dockerfile plugin has become out of date we've decided to remove it and use just a normal docker build after a mvn clean install
- Removed spotify dockerfile plugin
- Run `make build` and you should see it run mvn clean install and create a docker image with the jar afterwards
[Trello](https://trello.com/c/AHXXdTc5/)
> Removed dockerfile plugin from pom file

- Dockerfile
We currently use a full OpenJDK image for caseprocessor, rather than a slim/alpine version. On top of this the OpenJDK image page recommends not to use it and to instead use one with more support https://hub.docker.com/_/openjdk. We decided on the [eclipse-temurin](https://hub.docker.com/_/eclipse-temurin) image instead.
Changed base image to eclipse temurin alpine and updated Dockerfile to match
Tested by building and running image locally as well as deploying to a dev env and running acceptance tests against it
https://trello.com/c/XrY9QGaw
> Moved to eclipse temurin alpine base image

- pom.xml
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/CloudTaskMessage.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/CloudTaskPayload.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/CloudTaskType.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/EqFlushTaskPayload.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/CaseToProcessProcessor.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/EqFlushProcessor.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/ActionRuleProcessorTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/service/EqFlushProcessorTest.java
Adds an EQ flush action processor which sends flush cloud task messages for every launched, unreceipted QID linked to the cases it matches.
- Add EQ flush action processor
- Add cloud task DTO models
- Add tests
Build and run all the branches locally, run the ATs branch. Try creating/running an EQ Flush action rule from support tool.
https://trello.com/c/sN2EG6Rh/621-eq-flushing-by-action-rule-with-rate-limiting-13
> 621 Add eQ flush action rule processor

- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/ExportFileProcessor.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/utils/Constants.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/service/ExportFileProcessorTest.java
Export files needs to include sensitive data fields, when they are specifically addressed with a `__sensitive__.` prefix in the template.
- Include sensitive data fields in export file when addressed with `__sensitive__.` prefix in template
Build and run linked ATs branch
https://trello.com/c/WjIn0q5p/701-defect-information-marked-as-sensitive-missing-in-the-print-files
> 701 Include sensitive case fields in export files

- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/ExportFileDTO.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/model/dto/PayloadDTO.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/ExportFileProcessor.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/utils/EventHelper.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/service/ExportFileProcessorTest.java
We need the pack code to be logged in a query-able manner on `EXPORT_FILE` events. Putting it in the payload in the same format as we store it for other inbound events that we log is a simple solution.
- Store the export file pack code in the event payload of `EXPORT_FILE` events
- Update unit tests
Check the code, run locally, run an export file action rule, check the events have the pack code in the payload.
https://trello.com/c/Ve49M0OO/813-send-mi-to-phm-print-counts-5
> 813 Log payload containing pack code in EXPORT_FILE events

- .github/dependabot.yml
Dependabot PR isn't working for java repos
Added a dependabot.yml file to tell dependabot to use mvn 
This is a test to for a spike ([1146 Dependabot PR Spike](https://github.com/ONSdigital/ssdc-rm-documentation/pull/196))
Check its ok
[1146 Dependabot PR Spike](https://github.com/ONSdigital/ssdc-rm-documentation/pull/196)
https://trello.com/c/yzSbsXXs
> 1146 Dependabot PR

- .github/dependabot.yml
- pom.xml
All dependabot PRs are currently blocked because they don’t include our mandatory versioning labels, which obscures which ones pass the tests without a deeper dive.
Added  label to the dependabot config file
check it looks ok
https://trello.com/c/ZPLTDik6
> 1234 dependabot patch label

- .github/dependabot.yml
- Makefile
- pom.xml
The maven plugin we use for docker compose on our java projects is no longer compatible and we concluded the best solution was to create a custom script to replace this.
Changed the original plugin to a custom one
Amended make command that skips docker compose 
Check it works locally on your machine
(https://trello.com/c/yOWPLr4O)
> 1247 custom docker compose script

- .github/dependabot.yml
Dependabot currently raises PRs for all version updates, which is becoming too much for us to handle. 
Patch version updates are now ignored, which should hopefully reduce the number of PRs raised.
Merge it in and hope that the number of PRs reduces to a manageable level.  If it does then we can roll it out to other repos.
https://trello.com/c/JlchVJUn
> Ignore patch updates for Dependabot PRs

- .github/workflows/check-labels.yml
We're currently using version 1.2.7 of the github-pr-label-checker, which is a log way behind the most recent version 1.6.13.  Version 1.2.7 uses features that are now deprecated.
For info, Dependabot has already been set to avoid patch updates for this repo.
Updated the version of the label checker in the Git workflow.
This PR is the test.  I'll first allow it to run without a valid label then will add a label and allow it to re-run. It should continue to work as it always has.
https://trello.com/c/TDpQHGaw
> Update github-pr-label-checker to latest available version 1.6.13

- pom.xml
- src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/ActionRuleProcessor.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/schedule/CaseClassifier.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/schedule/ActionRuleIT.java
It would be useful to be able to see how many cases each action rule has selected in the support tool UI
Stored the number of selected cases returned by the case queuer against the respective action rule in the DB
Create a survey/CE/action rule in support tool and load a valid sample against it
Click the dry run button against the action rule and note how many cases should be picked up by that action rule
Wait for the rule to trigger and check that the number displayed against it in the 'Selected Cases' column is the same
> store count of selected cases against action rule

- src/main/java/uk/gov/ons/ssdc/caseprocessor/cache/UacQidCache.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/client/UacQidServiceClient.java
- src/main/java/uk/gov/ons/ssdc/caseprocessor/service/ExportFileProcessor.java
- src/main/resources/application-dev.yml
- src/test/java/uk/gov/ons/ssdc/caseprocessor/cache/UacQidCacheTest.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/EmailFulfilmentReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/messaging/SmsFulfilmentReceiverIT.java
- src/test/java/uk/gov/ons/ssdc/caseprocessor/service/ExportFileProcessorTest.java
We've decided that the questionnaire type doesn't need to be used as part of the qid now so we can remove it from the services requesting uacqid pairs. In Case Processor, this is a more involved change since the questionnaire type was used around the uacqid caching so that had to be changed slightly. It now locks on an object so whichever thread can lock on that object, can access the cache to top it up.
- Removed questionnaire type from the uacqid cache
- Changed the uacQidLinkQueueMap to just a blocking queue since there's no type to store uacs under.
- Changed the `shared-pubsub-project` variable in the dev application to our-project so it should work straight away instead of having to change the values.
- If the [uac-qid PR](https://github.com/ONSdigital/ssdc-rm-uac-qid-service/pull/64 …
> SDCSRM-487 Removing questionnaire type
